/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyecto2.view;

import com.proyecto2.controller.DiagramController;
import com.proyecto2.controller.GraphCreator;
import com.proyecto2.controller.JTreeController;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.proyecto2.files.*;
import com.proyecto2.structures.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ACER
 */
public class MainFrame extends javax.swing.JFrame {

    private XMLReader xmlReader;
    private TableLinkedList tableList;
    private JTreeController jTreeController;
    private DiagramController diagramController;
    private Graph graph;
    private GraphCreator graphCreator;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.xmlReader = new XMLReader();
        this.jTreeController = new JTreeController();
        this.diagramController = new DiagramController();
        this.graph = new Graph();
        this.graphCreator = new GraphCreator();
        this.jTextArea1.setEditable(false);
        this.jTextArea1.setText("En esta area de texto verá el contenido del archivo subido al sistema...");
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Tablas");
        DefaultTreeModel treeModel = new DefaultTreeModel(root);
        this.jTree2.setModel(treeModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archiveChargeButton = new javax.swing.JMenu();
        DiagramMenu = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        archiveChargeButton.setText("Cargar Archivo");
        archiveChargeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archiveChargeButtonMouseClicked(evt);
            }
        });
        jMenuBar1.add(archiveChargeButton);

        DiagramMenu.setText("Visualizar Diagrama de ER");
        DiagramMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DiagramMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(DiagramMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void archiveChargeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveChargeButtonMouseClicked
        JFileChooser fileChosser = new JFileChooser();
        int seleccion = fileChosser.showOpenDialog(this);
        this.jTextArea1.setText(" ");
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChosser.getSelectedFile();
            try {
                this.tableList = this.xmlReader.readXMLFile(selectedFile, this.jTextArea1, this);
                this.jTreeController.refreshJTree(this, jTree2, tableList);
                this.graph = this.graphCreator.createGraph(tableList, this.xmlReader.getRelationList());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo");
            }
        }
    }//GEN-LAST:event_archiveChargeButtonMouseClicked

    private void DiagramMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DiagramMenuMouseClicked
       this.diagramController.createGraph("graph.jpg", this.graph, this.tableList);
    }//GEN-LAST:event_DiagramMenuMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DiagramMenu;
    private javax.swing.JMenu archiveChargeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables
}
